# Generated by Django 2.2.5 on 2019-12-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='fridges',
            unique_together={('name', 'user')},
        ),
    ]
